# Generated by Django 5.1.2 on 2024-10-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
